; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = uno, ci

[env]
build_flags =
  -D SPECANN_APP=1
lib_deps =
  ../MAX2871_library_dev

[env:uno]
platform = atmelavr
board = uno
framework = arduino
build_flags =
  ${env.build_flags}
  -D SPECANN_TARGET_UNO=1

[env:ci]
platform = atmelavr
board = uno
framework = arduino
build_flags =
  ${env.build_flags}
  -D SPECANN_CI_BUILD=1
test_ignore = *
